export const ROUTES = {
  PUBLIC: {
    HOME: '/',
    SURVEY: '/survey',
    BYNUMBER: '/bynumber',
    REGISTER: {
      event: '/register?step=event',
      organization: '/register?step=organization',
      sport: '/register?step=sport',
      category: '/register?step=category',
      personalInfo: '/register?step=personal-info',
      confirmation: '/register?step=confirmation',
      completed: '/register?step=action',
    },
  },
  AUTH: {
    LOGIN: '/login',
  },
  ADMIN: {
    ROOT: '/admin',
    EVENTS: '/admin/events',
    EVENT: (id: string) => `/admin/events/${id}`,
    SPORTS: '/admin/sports',
    SPORT: (id: string) => `/admin/sports/${id}`,
    PARTICIPANTS: '/admin/participants',
    PROVINCES: '/admin/provinces',
    SURVEY: '/admin/survey',
  },
  SUPERADMIN: {
    ROOT: '/superadmin',
    EVENTS: '/superadmin/events',
    EVENT: (id: string) => `/superadmin/events/${id}`,
    SPORTS: '/superadmin/sports',
    SPORT: (id: string) => `/superadmin/sports/${id}`,
    PARTICIPANTS: '/superadmin/participants',
    PROVINCES: '/superadmin/provinces',
    SURVEY: '/superadmin/survey',
    USER: (id: string) => `/superadmin/users/${id}`,
    ORGANIZATIONS: '/superadmin/organizations',
    ORGANIZATION: (id: string) => `/superadmin/organizations/${id}`,
    CATEGORIES: '/superadmin/categories',
    MEDALS: '/superadmin/medals',
    LEADERBOARD: '/superadmin/leaderboard',
    ASSIGNMENTS: '/superadmin/assignments', // sports_event_org
    SESSIONS: '/superadmin/sessions', // refresh_tokens
    DASHBOARD: '/superadmin/dashboard',
  },
  API: {
    LOGIN: '/api/auth/login',
    LOGOUT: '/api/auth/logout',
    SESSION: '/api/auth/session',
    EVENTS: '/api/events',
    SPORTS: '/api/sports',
    REGISTRATIONS: '/api/registrations',
    PARTICIPANTS: '/api/participants',
    PROVINCES: '/api/provinces',
    ORGANIZATIONS: '/api/organizations',
    SURVEYS: '/api/surveys',
    DASHBOARD: '/api/dashboard',
    CATEGORIES: '/admin/categories',
    USERS: '/admin/users',
    MEDALS: '/admin/medals',
    LEADERBOARD: '/admin/leaderboard', // from participation_per_sport + medals
    SPORT_EVENT_ORGS: '/admin/assignments',
  },
} as const;
